[package]
name = "coffee-brewing-guide"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
measurements = "^0.9.0"
strum = "0.21"
strum_macros = "0.21"