name: deploy
on:
  workflow_run:
    branches: [main]
    workflows: [ci build]
    types: [completed]

defaults:
  run:
    working-directory: ./coffee-brewing-guide-web-ui


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0
      - uses: actions/checkout@v2

      - name: Trunk Build
        run: trunk build --release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coffee-brewing-guide-web-ui/dist
